[package]
name = "ruffle-android"
version = "0.1.0"
authors = ["TÖRÖK Attila <torokati44@gmail.com>"]
edition = "2018"
resolver = "2"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
wgpu = "0.14.0"
android-activity = { version = "0.4.0-beta", features = [ "game-activity" ]}
winit = { git = "https://github.com/rust-windowing/winit.git", branch = "master" }
#ndk-glue = { version = "0.7.0", features = ["logger"]}
ndk = { version = "0.7.0", features = ["audio"]}
async-executor = "1.0"
pollster = "0.2"
log = "0.4"
android_logger = "*"

ruffle_core = { git = "https://github.com/ruffle-rs/ruffle.git", branch = "master", features = [ "audio", "symphonia", "lzma" ] }
ruffle_render_wgpu = { git = "https://github.com/ruffle-rs/ruffle.git", branch = "master" }
ruffle_video = { git = "https://github.com/ruffle-rs/ruffle.git", branch = "master"}
ruffle_video_software = { git = "https://github.com/ruffle-rs/ruffle.git", branch = "master"}

jni = "0.19.0"
ndk-context = "0.1.0"


# one of these sections might not be needed...
[package.metadata.android]
build_targets = [ "aarch64-linux-android", "armv7-linux-androideabi" ]
target_sdk_version = 29
min_sdk_version = 26

[package.metadata.android.sdk]
build_targets = [ "aarch64-linux-android", "armv7-linux-androideabi" ]
target_sdk_version = 29
min_sdk_version = 26
